<div class="top-social-icons">
    <ul class="social-icons">
        <li class="social-icon social-icon-facebook">
            <a href="http://www.facebook.com/StudentKickOff" title="" target="_blank">Facebook</a>
        </li>
        <li class="social-icon social-icon-twitter">
            <a href="http://twitter.com/studentkickoff" title="" target="_blank">Twitter</a>
        </li>
        <li class="social-icon social-icon-instagram">
            <a href="#" title="">Instagram</a>
        </li>
    </ul>
</div>