<section class="picture-background front-background">
    <div class="container centered" id="countdown">
        <!-- <h1>Dit was Student Kick-Off 2013.<br /> <?php print l('Lees hier', 'nieuws/verslag-optredens-sko-13'); ?> de reviews van deze editie!</h1> -->
        <!-- <h1>Tot volgend jaar!</h1> -->

        <?php include('section-praktisch.inc'); ?>
    </div>
</section>

<section class="white-background">
    <?php include('social-icons.inc'); ?>
</section>
