<section class="picture-background">
    <div class="container centered" id="countdown">
        <h1 class="hidden">Countdown</h1>
        <div class="countdown-title">
            Student Kick&#45;off 2013<br />
            starting in
        </div>
        <span class="two-numbers">
            <span id="countdown-days">
                <span class="number">2</span>
                <span class="number">7</span>
            </span>
            <span class="number-sub">dagen</span>
        </span>
        <span class="two-numbers">
            <span id="countdown-hours">
                <span class="number">2</span>
                <span class="number">7</span>
            </span>
            <span class="number-sub">uren</span>
        </span>
        <span class="two-numbers">
            <span id="countdown-minutes">
                <span class="number">2</span>
                <span class="number">7</span>
            </span>
            <span class="number-sub">minuten</span>
        </span>
    </div>
</section>